# Generated by Django 2.2.3 on 2019-08-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
