# Generated by Django 2.2.3 on 2019-08-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissoes', '0002_auto_20190820_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='formacao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
