# Generated by Django 2.2.3 on 2019-08-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissoes', '0003_autor_formacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissao',
            name='arquivo',
            field=models.FileField(null=True, upload_to='submissoes/uploads'),
        ),
    ]
