# Generated by Django 2.2.3 on 2019-08-20 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissoes', '0004_auto_20190820_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='submetido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
