# Generated by Django 2.2.3 on 2019-08-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissoes', '0005_auto_20190820_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='formacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
