# Generated by Django 2.2.3 on 2019-08-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissoes', '0006_auto_20190829_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='aprovado',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='submissoes/uploads'),
        ),
    ]
